### PR TITLE
Get bbi on drone

### PR DESCRIPTION
**Pull request by seth127**
# Summary
This PR installs bbi on Drone and runs the tests that use it, except for the one test file that also uses NONMEM. That one (`tests/testthat/test-workflow-composable-bbi.R`) only runs on Metworx.

# Tests
- tests/testthat/test-rbabylon.R
  - check_bbi_exe() correctly errors or finds paths
  - bbi_init creates babylon.yaml
  - bbi_init errors with invalid .nonmem_version
- tests/testthat/test-summary.R
  - model_summary.bbi_nonmem_model produces expected output
  - model_summary.character produces expected output
  - model_summary.numeric produces expected output
  - model_summary() fails predictably if it can't find some parts (i.e. model isn't finished)
  - model_summary() fails predictably if no .lst file present
  - param_estimates() gets expected table

### CODE REVIEW

**Comment by shairozan** [comment]
One thing I would recommend is using a yaml anchor set to keep the URL in a global section. That keeps you from having to change it in multiple places:

```yml
#Gobal variable definitions and anchors
global-variables:
    environment: &default_environment
        BABYLON_URL: https://github.com/metrumresearchgroup/babylon/releases/download/v2.1.0-rc2/bbi_2.1.0-rc2_linux_amd64.tar.gz
        #Not currently used
        BABYLON_VERSION: 2.1.0-rc2

```

You can basically use the anchor to read in all the version into the environments:

```yml
- name: R36
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn:2020-01-29"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6/2020-01-29"
    # Reading in entire anchor
    <<: *default_environment
  commands:
  # download and setup bbi
  - wget $BABYLON_URL -O bbi.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi
  - mkdir -p /data/apps
  - mv bbi /data/apps/bbi
  - export PATH=/data/apps:$PATH
  # run R tests
  - /opt/R/3.6.2/bin/R -e "devtools::test()"
  - /opt/R/3.6.2/bin/R -e "devtools::check()"
```


Sometimes it's overkill (probably here ;)) But it's good to know you can do things like this with drone.

**Comment by shairozan** [comment]
Also the last RC ( [RC-3](https://github.com/metrumresearchgroup/babylon/releases/tag/v2.1.0-rc3) ) updated the Goreleaser name template to not include the path. So the following URLs are valid:

- [Mac (amd64)](https://www.github.com/metrumresearchgroup/babylon/releases/latest/download/bbi_darwin_amd64.tar.gz)
- [Linux (amd64)](https://www.github.com/metrumresearchgroup/babylon/releases/latest/download/bbi_linux_amd64.tar.gz)

These refer to the latest release in Babylon based on the Github specifications. You can use this to always target the current release

**Comment by seth127** [comment]
@shairozan so should I just use `https://www.github.com/metrumresearchgroup/babylon/releases/latest/download/bbi_linux_amd64.tar.gz` instead of the global variables you mentioned in your first comment?

**Comment by shairozan** [comment]
> @shairozan so should I just use `https://www.github.com/metrumresearchgroup/babylon/releases/latest/download/bbi_linux_amd64.tar.gz` instead of the global variables you mentioned in your first comment?

Not really. It still makes sense to me to use the global variables section to include the babylon URL from that one place into the environment at each step. The URL in that dictionary list would just be the link to the latest release I gave you.

This gives you a single dictionary to define common environment values in. Then you can refer to the environment variable in the individual steps as you go along.

**Pull request merged**
