### PR TITLE
Feat/summary print method

### LINKED ISSUE #121: Feature: one-pager run summary
# Summary
As a user, I want to be able to call a single R function and get a top-line summary of what happened in a nonmem run.  I want to summary to be plain text and resemble the output from `bbi nonmem summary`

# Tests

### PR DESCRIPTION
**Pull request by seth127**
Closes #121

### CODE REVIEW

**Comment by seth127** [comment]
Note: I added a new model at `inst/model/nonmem/complex/acop-iov` primarily for testing the print method. The changes to `test-summary-log.R` also reflect adding this model the folder that is being checked by that test.

**Review by annacnev — DISMISSED** [review]
looks good to me - except for manual making of bulleted lists.

**Review by annacnev — DISMISSED** [review]
I dig it - lets gooo rbabylon 2.3.1

**Comment by seth127** [comment]
Merged as administrator because @annacnev already approved yesterday and all that has changed is some commit squashing. (And Anna is out today through the rest of the year.)

**Pull request merged**
